#!/bin/bash
#
# This file is part of the Simutrans project under the Artistic License.
# (see LICENSE.txt)
#
# Authenticated encryption for the preserved build artifact.
#
# Meant to be sourced, not executed.
#
#
# The specification, in full
# --------------------------
#   tool        GnuPG (gpg), preinstalled on the GitHub macOS runner images.
#               Chosen over installing something else because the job that
#               runs it also holds the Developer ID, and adding a network
#               fetch and a third-party binary to that job is a cost with no
#               benefit here.
#   container   OpenPGP symmetric-key encrypted message, packet version 5
#   cipher      AES-256                                   (OpenPGP cipher 9)
#   mode        OCB, an AEAD mode specified in RFC 7253   (OpenPGP aead 2)
#   tag         OCB's authentication tag, 16 octets as libgcrypt produces it.
#               NOTE: the `cb=` value in --list-packets is NOT the tag length.
#               It is the chunk-size octet: the chunk is 2^(cb+6) octets, so
#               cb=16 means 4 MiB chunks.  Measured by varying --chunk-size:
#                 --chunk-size 10 -> cb=4 ; 16 -> cb=10 ; 22 -> cb=16
#   nonce/IV    per-message and per-chunk, generated by GnuPG.  Not managed
#               here on purpose: hand-rolling nonces is how AEAD gets broken.
#   key         MACOS_ARTIFACT_KEY, a passphrase.  It is expected to be 32
#               random bytes in base64 (`openssl rand -base64 32`), and is
#               additionally stretched by OpenPGP S2K mode 3 (iterated and
#               salted) with SHA-512.  The count is 65011712 OCTETS FED TO THE
#               HASH, not iterations: RFC 9580 says "the total number of
#               octets to be hashed is specified in the encoded count".  That
#               is the largest value the one-octet encoding can represent;
#               GnuPG accepts larger numbers and rounds rather than failing.
#   integrity   the OCB tag authenticates the whole message.  Decryption of a
#               modified or truncated message fails; it does not return
#               plaintext.
#   metadata    the authoritative manifest is INSIDE the encrypted container,
#               so it is covered by that same tag.  Anything left outside is
#               descriptive only and is treated as untrusted.
#
# Measured on GnuPG 2.4.9, and the reason every call below is explicit:
#
#   gpg --symmetric --cipher-algo AES256          -> ":symkey enc packet: ... aead 0"
#                                                    ":encrypted data packet: mdc_method: 2"
#   ... --force-aead --aead-algo OCB              -> ":aead encrypted packet: cipher=9 aead=2 cb=16"
#
# Be precise about what that first line means.  It is NOT an unprotected
# message: OpenPGP's classic mode carries a Modification Detection Code, and
# GnuPG refuses to hand back plaintext when the MDC fails.  What it is not is
# AEAD - the MDC is a SHA-1 construction bolted onto CFB rather than a modern
# authenticated mode, and it is the weaker of the two.  AEAD is asked for
# because it is better, not because the alternative is naked.
#
# (The thing that genuinely had no integrity protection was the earlier
# implementation of this file, which used `openssl enc -aes-256-cbc`.)
#
# Because a default can move in either direction, every message this produces
# is inspected afterwards and rejected if it is not AES-256 OCB.

# shellcheck disable=SC2034  # consumed by the scripts that source this file
ARTIFACT_CONTAINER_SCHEMA='simutrans-macos-signed-artifact/2'

# OpenPGP numbers, checked against the packet dump rather than trusted.
_ARTIFACT_CIPHER_AES256=9
_ARTIFACT_AEAD_OCB=2

_gpg_common=(
	--batch --yes --quiet --no-tty
	--pinentry-mode loopback
	--passphrase-fd 0
)

_gpg_encrypt_opts=(
	--symmetric
	--cipher-algo AES256
	--force-aead
	--aead-algo OCB
	--s2k-mode 3
	--s2k-digest-algo SHA512
	--s2k-count 65011712
	--compress-algo none
)

# ---------------------------------------------------------------------------
# artifact_key_present
#
# Only checks that something is configured.  Whether it is the right key is a
# different question, answered by artifact_selftest.
# ---------------------------------------------------------------------------
artifact_key_present() {
	[ -n "${MACOS_ARTIFACT_KEY:-}" ]
}

# ---------------------------------------------------------------------------
# artifact_assert_aead <file>
#
# Refuses a message that is not AES-256 in OCB.  This is the check that makes
# the "did the tool actually do what we asked" question answerable instead of
# assumed.
# ---------------------------------------------------------------------------
artifact_assert_aead() {
	local f=$1 packets
	packets=$(gpg --list-packets --list-only "$f" 2>/dev/null || true)
	if ! grep -q ':aead encrypted packet:' <<<"$packets"; then
		echo "::error::the encrypted container is not an AEAD message."
		echo "::error::gpg produced this instead:"
		printf '%s\n' "$packets" | sed 's/^/::error::  /'
		echo "::error::This may still be an integrity-protected OpenPGP message - the"
		echo "::error::classic mode carries an MDC - but it is not the authenticated mode"
		echo "::error::this container is specified to use, so it is refused."
		return 1
	fi
	if ! grep -qE ":aead encrypted packet: cipher=$_ARTIFACT_CIPHER_AES256 aead=$_ARTIFACT_AEAD_OCB " <<<"$packets"; then
		echo "::error::unexpected cipher or AEAD mode:"
		printf '%s\n' "$packets" | grep ':aead encrypted packet:' | sed 's/^/::error::  /'
		echo "::error::Expected cipher=$_ARTIFACT_CIPHER_AES256 (AES-256) aead=$_ARTIFACT_AEAD_OCB (OCB)."
		return 1
	fi
	return 0
}

# ---------------------------------------------------------------------------
# artifact_encrypt <plaintext> <ciphertext>
# ---------------------------------------------------------------------------
artifact_encrypt() {
	local in=$1 out=$2
	artifact_key_present || { echo "::error::MACOS_ARTIFACT_KEY is not set."; return 1; }
	umask 077
	if ! printf '%s' "$MACOS_ARTIFACT_KEY" \
			| gpg "${_gpg_common[@]}" "${_gpg_encrypt_opts[@]}" --output "$out" "$in"; then
		echo "::error::encryption failed."
		return 1
	fi
	artifact_assert_aead "$out" || return 1
	return 0
}

# ---------------------------------------------------------------------------
# artifact_decrypt <ciphertext> <plaintext>
#
# The AEAD tag is verified by gpg as part of decryption: a failure here means
# wrong key, or a message that has been altered or truncated.  It never means
# "here is the plaintext anyway".
# ---------------------------------------------------------------------------
artifact_decrypt() {
	local in=$1 out=$2
	artifact_key_present || { echo "::error::MACOS_ARTIFACT_KEY is not set."; return 1; }
	artifact_assert_aead "$in" || return 1
	umask 077
	if ! printf '%s' "$MACOS_ARTIFACT_KEY" \
			| gpg "${_gpg_common[@]}" --decrypt --output "$out" "$in" 2>/dev/null; then
		rm -f "$out"
		echo "::error::decryption failed: wrong key, or the container has been altered."
		return 1
	fi
	return 0
}

# ---------------------------------------------------------------------------
# artifact_selftest
#
# Encrypts and decrypts a probe with the configured key, so that a missing or
# unusable key is discovered BEFORE the signing identity is loaded rather than
# after a bundle has been signed.
#
# What it cannot tell you: whether the upload will succeed later.  That has
# not happened yet, and pretending otherwise would be a false promise.
# ---------------------------------------------------------------------------
artifact_selftest() {
	local d rc=0
	artifact_key_present || {
		echo "::error::MACOS_ARTIFACT_KEY is not set."
		return 1
	}
	d=$(mktemp -d "${RUNNER_TEMP:-/tmp}/simu-artifact-probe.XXXXXX")
	printf 'simutrans artifact retention probe\n' > "$d/probe"
	if artifact_encrypt "$d/probe" "$d/probe.gpg" && \
	   artifact_decrypt "$d/probe.gpg" "$d/probe.back" && \
	   cmp -s "$d/probe" "$d/probe.back"; then
		echo "retention self-test passed: AES-256 OCB round trip with the configured key"
	else
		echo "::error::retention self-test failed: the configured key cannot encrypt and"
		echo "::error::decrypt a probe.  Nothing has been signed yet, and nothing will be."
		rc=1
	fi
	rm -rf "$d"
	return "$rc"
}
